# Loading data into pandas dataframe





In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split  

df = pd.read_csv("online_shoppers_intention_numbers.csv")

print(df.columns)

#splitting the Class variable and the features
X = df.drop(columns=['Revenue'])
Y = df['Revenue']

#Making different datasets based on the top 10 features for testing purposes
datasets = {}

X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.2, random_state = 32342) 

Index(['Administrative', 'Administrative_Duration', 'Informational',
       'Informational_Duration', 'ProductRelated', 'ProductRelated_Duration',
       'BounceRates', 'ExitRates', 'PageValues', 'SpecialDay', 'Month',
       'OperatingSystems', 'Browser', 'Region', 'TrafficType', 'VisitorType',
       'Weekend', 'Revenue'],
      dtype='object')


In [20]:
# added by Duc, data nomalization
#from sklearn.preprocessing import MinMaxScaler
#scaler = MinMaxScaler()
#scaler.fit(X_train)
#X_train_scaled = scaler.transform(X_train)
#X_test_scaled = scaler.transform(X_test)


#Commented out because datasets transformation in the follwing block of code cannot be done when 

In [2]:
print("Original data")
print(X_train[0:9][:])

Original data
       Administrative  Administrative_Duration  Informational  \
2637               14               230.106944              0   
9415                5               158.700000              0   
11579              11               449.750000              0   
6437                1                22.200000              2   
2198                0                 0.000000              0   
11826               0                 0.000000              4   
5663                0                 0.000000              0   
9553                1                 3.000000              0   
2084                1                 5.000000              0   

       Informational_Duration  ProductRelated  ProductRelated_Duration  \
2637                     0.00              52              2059.109203   
9415                     0.00              51              1364.266667   
11579                    0.00              52              1786.109649   
6437                    44.40          

In [19]:
print("Scaled data")
print(X_train_scaled[0:9][:])


Scaled data
[[5.18518519e-01 6.77034040e-02 0.00000000e+00 0.00000000e+00
  7.37588652e-02 3.21868975e-02 1.87353650e-02 4.22556200e-02
  2.64293485e-02 0.00000000e+00 3.00000000e-01 1.42857143e-01
  8.33333333e-02 0.00000000e+00 6.31578947e-01 5.00000000e-01
  0.00000000e+00]
 [1.85185185e-01 4.66936374e-02 0.00000000e+00 0.00000000e+00
  7.23404255e-02 2.13254894e-02 3.84615400e-02 5.99358950e-02
  0.00000000e+00 0.00000000e+00 9.00000000e-01 2.85714286e-01
  8.33333333e-02 2.50000000e-01 5.26315789e-02 5.00000000e-01
  1.00000000e+00]
 [4.07407407e-01 1.32328062e-01 0.00000000e+00 0.00000000e+00
  7.37588652e-02 2.79195140e-02 0.00000000e+00 8.55932200e-02
  1.41191793e-01 0.00000000e+00 9.00000000e-01 0.00000000e+00
  0.00000000e+00 0.00000000e+00 5.26315789e-02 5.00000000e-01
  0.00000000e+00]
 [3.70370370e-02 6.53181317e-03 8.33333333e-02 1.74160333e-02
  5.24822695e-02 6.26509196e-03 2.56410250e-02 1.28205150e-02
  0.00000000e+00 0.00000000e+00 8.00000000e-01 1.42857143e-01
  7.

In [3]:


datasets.update({"17" : { "X_train": X_train, "X_test": X_test}})
datasets.update({"10" : { "X_train": datasets["17"]["X_train"].drop(columns =['Month', 'TrafficType', 'Informational_Duration', 'OperatingSystems', 'Weekend','Region','Browser']),
                                                 "X_test" : datasets["17"]["X_test"].drop(columns =['Month', 'TrafficType', 'Informational_Duration', 'OperatingSystems', 'Weekend','Region','Browser'])}})
datasets.update({"9": { "X_train": datasets["10"]["X_train"].drop(columns =['SpecialDay']), 
                       "X_test": datasets["10"]["X_test"].drop(columns = ['SpecialDay'])}})
datasets.update({"8": { "X_train": datasets["9"]["X_train"].drop(columns =['Administrative_Duration']), 
                       "X_test": datasets["9"]["X_test"].drop(columns = ['Administrative_Duration'])}})
datasets.update({"7": { "X_train": datasets["8"]["X_train"].drop(columns =['Informational']), 
                       "X_test": datasets["8"]["X_test"].drop(columns = ['Informational'])}})
datasets.update({"6": { "X_train": datasets["7"]["X_train"].drop(columns =['VisitorType']), 
                       "X_test": datasets["7"]["X_test"].drop(columns = ['VisitorType'])}})
datasets.update({"5": { "X_train": datasets["6"]["X_train"].drop(columns =['Administrative']), 
                       "X_test": datasets["6"]["X_test"].drop(columns = ['Administrative'])}})
datasets.update({"4": { "X_train": datasets["5"]["X_train"].drop(columns =['BounceRates']), 
                       "X_test": datasets["5"]["X_test"].drop(columns = ['BounceRates'])}})
datasets.update({"3": { "X_train": datasets["4"]["X_train"].drop(columns =['ProductRelated_Duration']), 
                       "X_test": datasets["4"]["X_test"].drop(columns = ['ProductRelated_Duration'])}})
datasets.update({"2": { "X_train": datasets["3"]["X_train"].drop(columns =['ProductRelated']), 
                       "X_test": datasets["3"]["X_test"].drop(columns = ['ProductRelated'])}})
datasets.update({"1": { "X_train": datasets["2"]["X_train"].drop(columns =['ExitRates']), 
                       "X_test": datasets["2"]["X_test"].drop(columns = ['ExitRates'])}})


#for dataset in datasets:
#    print(datasets[dataset])

print(Y.values)
print(datasets["5"]["X_train"])

[0 0 0 ... 0 0 0]
       ProductRelated  ProductRelated_Duration  BounceRates  ExitRates  \
2637               52              2059.109203     0.003747   0.008451   
9415               51              1364.266667     0.007692   0.011987   
11579              52              1786.109649     0.000000   0.017119   
6437               37               400.800000     0.005128   0.002564   
2198                2               162.000000     0.000000   0.050000   
...               ...                      ...          ...        ...   
8136               22              2281.583333     0.029697   0.043687   
12078              45              1896.966667     0.011765   0.027451   
7077               26               710.000000     0.003846   0.017521   
4891               21               204.166667     0.028571   0.048413   
4679               15               537.200000     0.011765   0.023529   

       PageValues  
2637     7.610431  
9415     0.000000  
11579   40.656712  
6437     0.00

In [4]:
# added by Duc for debugging
print("Train data size", X_train.shape, y_train.shape)
print("Train test size", X_test.shape, y_test.shape)

Train data size (9864, 17) (9864,)
Train test size (2466, 17) (2466,)


In [5]:
# added by Duc
import collections
print("number of examples per class in train set:", collections.Counter(y_train))
print("number of examples per class in test set:", collections.Counter(y_test))

number of examples per class in train set: Counter({0: 8357, 1: 1507})
number of examples per class in test set: Counter({0: 2065, 1: 401})


In [8]:
from sklearn.manifold import TSNE 
import matplotlib.pyplot as plt 
%matplotlib inline
import seaborn as sns 

def tsne_plot(x, y):

    sns.set(style ="whitegrid") 
      
    tsne = TSNE(n_components = 2, random_state = 0) 
      
    # Reducing the dimensionality of the data 
    X_transformed = tsne.fit_transform(x) 
  
    plt.figure(figsize =(12, 8)) 
      
    # Building the scatter plot 
    plt.scatter(X_transformed[np.where(y == 0), 0],  
                X_transformed[np.where(y == 0), 1], 
                marker ='o', color ='y', linewidth ='1', 
                alpha = 0.8, label ='Non-Buyer') 
    plt.scatter(X_transformed[np.where(y == 1), 0], 
                X_transformed[np.where(y == 1), 1], 
                marker ='o', color ='k', linewidth ='1', 
                alpha = 0.8, label ='Buyer') 
  
    # Specifying the location of the legend 
    plt.legend(loc ='best') 
      
    # Plotting the reduced data 
    plt.show() 

#tsne_plot(X, Y)

In [6]:

from sklearn.preprocessing import MinMaxScaler



for dataset in datasets:
        
        
    scaler = MinMaxScaler()
    scaler.fit(datasets[dataset]["X_train"])
    X_train_scaled = scaler.transform(datasets[dataset]["X_train"])
    X_test_scaled = scaler.transform(datasets[dataset]["X_test"])
    datasets[dataset].update({"X_train": X_train_scaled, 
                                "X_test" : X_test_scaled})
    
    
   # datasets[dataset] = scaler.fit_transform(datasets[dataset])
    
#scaled_datasets['10'] = X_scaled.drop(columns = ['Month', 'Traffictype', 'Informational_Duration', 'OperatingSystems', 'Weekend','Region','Browser'])
#scaled_datasets['9'] = X10_scaled.drop(columns =['SpecialDay'])
#scaled_datasets['8'] = X9_scaled.drop(columns = ['Administrative_Duration'])
#scaled_datasets['7'] = X8_scaled.drop(columns = ['Informational'])
#scaled_datasets['6'] = X7_scaled.drop(columns = ['VisitorType'])
#scaled_datasets['5'] = X6_scaled.drop(columns = ['Administrative'])
#scaled_datasets['4'] = X5_scaled.drop(columns = ['BounceRates'])
#scaled_datasets['3'] = X4_scaled.drop(columns = ['ProductRelated_Duration'])
#scaled_datasets['2'] = X3_scaled.drop(columns = ['ProductRelated'])
#scaled_datasets['1'] = X2_scaled.drop(columns = ['ExitRates'])




#tsne_plot(X_scaled, Y)

In [7]:
from sklearn.svm import SVC 
from sklearn.metrics import accuracy_score, confusion_matrix 

# Splitting dataset into train set and test set.
def makepredictions(datasets):
    
    for dataset in datasets:
    
     #   X_train, X_test, y_train, y_test = train_test_split(datasets[dataset], Y, test_size = 0.2, random_state = 32342) 


        svmclf = SVC() 
        svmclf.fit(datasets[dataset]["X_train"], y_train) 

        y_pred_svmclf = svmclf.predict(datasets[dataset]["X_test"]) 
  
        # Performance
        print('amount of features: ' + dataset)
        print('Accuracy : '+str(accuracy_score(y_test, y_pred_svmclf))) 
        print('Confusion Matrix: \n' + str(confusion_matrix(y_test,y_pred_svmclf)))
        # incorrect order of output
#         tn, fn, fp, tp = confusion_matrix(y_test, y_pred_svmclf).ravel()
        # the right order is as follows
        tn, fp, fn, tp = confusion_matrix(y_test, y_pred_svmclf).ravel()
    
        print('True negatives: ' + str(tn) + '\n' + 'False positives: ' + str(fp) +  '\n' + 'False negatives: ' + str(fn) + '\n'+ 'True positives: ' + str(tp) + '\n')

makepredictions(datasets)

amount of features: 17
Accuracy : 0.8807785888077859
Confusion Matrix: 
[[2030   35]
 [ 259  142]]
True negatives: 2030
False positives: 35
False negatives: 259
True positives: 142

amount of features: 10
Accuracy : 0.8868613138686131
Confusion Matrix: 
[[2018   47]
 [ 232  169]]
True negatives: 2018
False positives: 47
False negatives: 232
True positives: 169

amount of features: 9
Accuracy : 0.8872668288726683
Confusion Matrix: 
[[2018   47]
 [ 231  170]]
True negatives: 2018
False positives: 47
False negatives: 231
True positives: 170

amount of features: 8
Accuracy : 0.8872668288726683
Confusion Matrix: 
[[2017   48]
 [ 230  171]]
True negatives: 2017
False positives: 48
False negatives: 230
True positives: 171

amount of features: 7
Accuracy : 0.8876723438767234
Confusion Matrix: 
[[2018   47]
 [ 230  171]]
True negatives: 2018
False positives: 47
False negatives: 230
True positives: 171

amount of features: 6
Accuracy : 0.8888888888888888
Confusion Matrix: 
[[2013   52]
 [ 222  1

In [18]:
from keras.layers import Input, Dense 
from keras.models import Model, Sequential 
from keras import regularizers 
from keras.layers import Input, Dense, Conv2D, MaxPooling2D, UpSampling2D
from keras import backend as K

#scaler = MinMaxScaler()

#X_scaled = scaler.fit_transform(X)
#X_nonbuyer_scaled = X_scaled[Y == 0] 
#X_buyer_scaled = X_scaled[Y == 1]
i = 1
for i in range(1,11): 

    input_layer = Input(shape =(X.shape[1], )) 

    #Encoder network Deep
    encoded_deep = Dense(100, activation ='tanh')(input_layer) 
    encoded_deep = Dense(50, activation ='tanh')(encoded_deep) 
    encoded_deep = Dense(25, activation ='tanh')(encoded_deep) 
    encoded_deep = Dense(12, activation ='tanh')(encoded_deep) 
    encoded_deep = Dense(i, activation ='relu')(encoded_deep) 

    #Decoder network deep
    decoded_deep = Dense(12, activation ='tanh')(encoded_deep) 
    decoded_deep = Dense(25, activation ='tanh')(decoded_deep) 
    decoded_deep = Dense(50, activation ='tanh')(decoded_deep) 
    decoded_deep = Dense(100, activation ='tanh')(decoded_deep) 

    output_layer_deep = Dense(X.shape[1], activation ='relu')(decoded_deep) 



        # Defining the parameters of the Auto-encoder network 
    autoencoder = Model(input_layer, output_layer_deep) 
    autoencoder.compile(optimizer ="adadelta", loss ="mse") 

        # Training the Auto-encoder network 
    autoencoder.fit(datasets["17"]["X_train"],datasets["17"]["X_train"],  
                        batch_size = 3000, epochs = 10,  
                        shuffle = True, validation_split = 0.2) 


    hidden_representation = Sequential() 
    hidden_representation.add(autoencoder.layers[0]) 
    hidden_representation.add(autoencoder.layers[1]) 
    hidden_representation.add(autoencoder.layers[2]) 
    hidden_representation.add(autoencoder.layers[3]) 
    hidden_representation.add(autoencoder.layers[4]) 

        # Separating the points encoded by the Auto-encoder as normal and fraud 
        #nonbuyer_hidden_rep = hidden_representation.predict(X_nonbuyer_scaled) 
        #buyer_hidden_rep = hidden_representation.predict(X_buyer_scaled) 

        # Combining the encoded points into a single table  
        #encoded_X = np.append(nonbuyer_hidden_rep, buyer_hidden_rep, axis = 0) 
        #y_nonbuyer = np.zeros(nonbuyer_hidden_rep.shape[0]) 
        #y_buyer = np.ones(buyer_hidden_rep.shape[0]) 
        #encoded_y = np.append(y_nonbuyer, y_buyer) 
    encoded_X_train = hidden_representation.predict(datasets["17"]["X_train"]) 

    encoded_X_test = hidden_representation.predict(datasets["17"]["X_test"])


    classifier = SVC() 
    classifier.fit(encoded_X_train, y_train) 

        # Storing the predictions of the linear model 
    y_pred_classifier = classifier.predict(encoded_X_test) 


        # Plotting the encoded points 
        #tsne_plot(encoded_X, encoded_y) 


        # Performance
    print('amount of features: '+ str(i))
    print('Accuracy : '+str(accuracy_score(y_test, y_pred_classifier))) 
    print('Confusion Matrix: \n' + str(confusion_matrix(y_test,y_pred_classifier)))
    tn, fp, fn, tp = confusion_matrix(y_test, y_pred_classifier).ravel()

    print('True negatives: ' + str(tn) + '\n' + 'False positives: ' + str(fp) +  '\n' + 'False negatives: ' + str(fn) + '\n'+ 'True positives: ' + str(tp) + '\n')

    i = i + 1

Train on 7891 samples, validate on 1973 samples
Epoch 1/10
7891/7891 [==============================] - 0s 44us/step - loss: 0.0828 - val_loss: 0.0759
Epoch 2/10
7891/7891 [==============================] - 0s 3us/step - loss: 0.0738 - val_loss: 0.0691
Epoch 3/10
7891/7891 [==============================] - 0s 3us/step - loss: 0.0679 - val_loss: 0.0664
Epoch 4/10
7891/7891 [==============================] - 0s 3us/step - loss: 0.0655 - val_loss: 0.0651
Epoch 5/10
7891/7891 [==============================] - 0s 3us/step - loss: 0.0640 - val_loss: 0.0638
Epoch 6/10
7891/7891 [==============================] - 0s 3us/step - loss: 0.0626 - val_loss: 0.0621
Epoch 7/10
7891/7891 [==============================] - 0s 3us/step - loss: 0.0604 - val_loss: 0.0555
Epoch 8/10
7891/7891 [==============================] - 0s 3us/step - loss: 0.0515 - val_loss: 0.0442
Epoch 9/10
7891/7891 [==============================] - 0s 3us/step - loss: 0.0425 - val_loss: 0.0399
Epoch 10/10
7891/7891 [==========

7891/7891 [==============================] - 0s 4us/step - loss: 0.0416 - val_loss: 0.0368
Epoch 8/10
7891/7891 [==============================] - 0s 3us/step - loss: 0.0373 - val_loss: 0.0359
Epoch 9/10
7891/7891 [==============================] - 0s 3us/step - loss: 0.0365 - val_loss: 0.0349
Epoch 10/10
7891/7891 [==============================] - 0s 3us/step - loss: 0.0351 - val_loss: 0.0319
amount of features: 7
Accuracy : 0.8386050283860503
Confusion Matrix: 
[[2065    0]
 [ 398    3]]
True negatives: 2065
False positives: 0
False negatives: 398
True positives: 3

Train on 7891 samples, validate on 1973 samples
Epoch 1/10
7891/7891 [==============================] - 0s 41us/step - loss: 0.0751 - val_loss: 0.0669
Epoch 2/10
7891/7891 [==============================] - 0s 3us/step - loss: 0.0652 - val_loss: 0.0637
Epoch 3/10
7891/7891 [==============================] - 0s 3us/step - loss: 0.0625 - val_loss: 0.0623
Epoch 4/10
7891/7891 [==============================] - 0s 3us/step -

In [21]:
i = 1
for i in range(1,11): 


    input_layer_sparse = Input(shape =(X.shape[1], )) 



    #Encoder network Sparsity constraint
    encoded_sparse = Dense(100, activation ='tanh',
    activity_regularizer = regularizers.l1(10e-5))(input_layer_sparse) 
    encoded_sparse = Dense(50, activation ='tanh',
    activity_regularizer = regularizers.l1(10e-5))(encoded_sparse) 
    encoded_sparse = Dense(25, activation ='tanh', 
    activity_regularizer = regularizers.l1(10e-5))(encoded_sparse) 
    encoded_sparse = Dense(12, activation ='tanh', 
    activity_regularizer = regularizers.l1(10e-5))(encoded_sparse) 
    encoded_sparse = Dense(i, activation ='relu')(encoded_sparse) 

    #Decoder network Sparsity constraint
    decoded_sparse = Dense(12, activation ='tanh')(encoded_sparse) 
    decoded_sparse = Dense(25, activation ='tanh')(decoded_sparse) 
    decoded_sparse = Dense(50, activation ='tanh')(decoded_sparse) 
    decoded_sparse = Dense(100, activation ='tanh')(decoded_sparse) 

    output_layer_sparse = Dense(X.shape[1], activation ='relu')(decoded_sparse) 



    # Defining the parameters of the Auto-encoder network 
    autoencoder = Model(input_layer_sparse, output_layer_sparse) 
    autoencoder.compile(optimizer ="adadelta", loss ="mse") 

    # Training the Auto-encoder network 
    autoencoder.fit(datasets["17"]["X_train"], datasets["17"]["X_train"],  
                        batch_size = 3000, epochs = 10,  
                        shuffle = True, validation_split = 0.2) 


    hidden_representation = Sequential() 
    hidden_representation.add(autoencoder.layers[0]) 
    hidden_representation.add(autoencoder.layers[1]) 
    hidden_representation.add(autoencoder.layers[2]) 
    hidden_representation.add(autoencoder.layers[3]) 
    hidden_representation.add(autoencoder.layers[4]) 

        # Separating the points encoded by the Auto-encoder as normal and fraud 
        #nonbuyer_hidden_rep = hidden_representation.predict(X_nonbuyer_scaled) 
        #buyer_hidden_rep = hidden_representation.predict(X_buyer_scaled) 

        # Combining the encoded points into a single table  
        #encoded_X = np.append(nonbuyer_hidden_rep, buyer_hidden_rep, axis = 0) 
        #y_nonbuyer = np.zeros(nonbuyer_hidden_rep.shape[0]) 
        #y_buyer = np.ones(buyer_hidden_rep.shape[0]) 
        #encoded_y = np.append(y_nonbuyer, y_buyer) 
    encoded_X_train = hidden_representation.predict(datasets["17"]["X_train"]) 

    encoded_X_test = hidden_representation.predict(datasets["17"]["X_test"])


    classifier = SVC() 
    classifier.fit(encoded_X_train, y_train) 

        # Storing the predictions of the linear model 
    y_pred_classifier = classifier.predict(encoded_X_test) 


        # Plotting the encoded points 
        #tsne_plot(encoded_X, encoded_y) 


        # Performance
    print('amount of features: '+ str(i))
    print('Accuracy : '+str(accuracy_score(y_test, y_pred_classifier))) 
    print('Confusion Matrix: \n' + str(confusion_matrix(y_test,y_pred_classifier)))
    tn, fp, fn, tp = confusion_matrix(y_test, y_pred_classifier).ravel()

    print('True negatives: ' + str(tn) + '\n' + 'False positives: ' + str(fp) +  '\n' + 'False negatives: ' + str(fn) + '\n'+ 'True positives: ' + str(tp) + '\n')
    i = i + 1

Train on 7891 samples, validate on 1973 samples
Epoch 1/10
7891/7891 [==============================] - 0s 47us/step - loss: 6.0726 - val_loss: 3.9220
Epoch 2/10
7891/7891 [==============================] - 0s 3us/step - loss: 5.2437 - val_loss: 3.4976
Epoch 3/10
7891/7891 [==============================] - 0s 4us/step - loss: 4.7377 - val_loss: 3.1996
Epoch 4/10
7891/7891 [==============================] - 0s 3us/step - loss: 4.3679 - val_loss: 2.9640
Epoch 5/10
7891/7891 [==============================] - 0s 3us/step - loss: 4.0714 - val_loss: 2.7639
Epoch 6/10
7891/7891 [==============================] - 0s 3us/step - loss: 3.8019 - val_loss: 2.6025
Epoch 7/10
7891/7891 [==============================] - 0s 3us/step - loss: 3.5983 - val_loss: 2.4529
Epoch 8/10
7891/7891 [==============================] - 0s 3us/step - loss: 3.3919 - val_loss: 2.3276
Epoch 9/10
7891/7891 [==============================] - 0s 3us/step - loss: 3.2283 - val_loss: 2.2166
Epoch 10/10
7891/7891 [==========

7891/7891 [==============================] - 0s 3us/step - loss: 3.4864 - val_loss: 2.3921
Epoch 8/10
7891/7891 [==============================] - 0s 4us/step - loss: 3.2870 - val_loss: 2.2609
Epoch 9/10
7891/7891 [==============================] - 0s 3us/step - loss: 3.1103 - val_loss: 2.1615
Epoch 10/10
7891/7891 [==============================] - 0s 3us/step - loss: 3.0119 - val_loss: 2.0544
amount of features: 7
Accuracy : 0.8714517437145174
Confusion Matrix: 
[[2038   27]
 [ 290  111]]
True negatives: 2038
False positives: 27
False negatives: 290
True positives: 111

Train on 7891 samples, validate on 1973 samples
Epoch 1/10
7891/7891 [==============================] - 0s 49us/step - loss: 6.6179 - val_loss: 4.2664
Epoch 2/10
7891/7891 [==============================] - 0s 4us/step - loss: 5.6546 - val_loss: 3.7607
Epoch 3/10
7891/7891 [==============================] - 0s 3us/step - loss: 5.0231 - val_loss: 3.3909
Epoch 4/10
7891/7891 [==============================] - 0s 3us/ste

In [23]:
#Encoder network Convolutional
i = 1
for i in range(1, 11):
    

    #print(X.shape[0])
    X_train_conv = X_train.drop(columns =['OperatingSystems'])
    X_test_conv = X_test.drop(columns = ['OperatingSystems'])
    scaler = MinMaxScaler()
    scaler.fit(X_train_conv)
    X_train_scaled_conv = scaler.transform(X_train_conv)
    X_test_scaled_conv = scaler.transform(X_test_conv)
    #print(X_train_scaled_conv.shape[1])
    #print(X_test_scaled_conv.shape[1])
    #print("Train data size", X_train_scaled_conv.shape, y_train.shape)
    #print("Train test size", X_test_scaled_conv.shape, y_test.shape)
    X_train_scaled_conv = np.reshape(X_train_scaled_conv, (len(X_train_scaled_conv), 4, 4, 1))  # adapt this if using `channels_first` image data format
    X_test_scaled_conv = np.reshape(X_test_scaled_conv, (len(X_test_scaled_conv), 4, 4, 1))  # adapt this if using `channels_first` image data format

    input_layer = Input(shape =(4,4,1))

    x = Conv2D(16, (2, 2), activation='relu', padding='same')(input_layer)
    x = MaxPooling2D((2, 2), padding='same')(x)
    x = Conv2D(i, (2, 2), activation='relu', padding='same')(x)
    encoded_conv = MaxPooling2D((2, 2), padding='same')(x)

    # at this point the representation is (4, 4, 8) i.e. 128-dimensional

    x = Conv2D(i, (2, 2), activation='relu', padding='same')(encoded_conv)
    x = UpSampling2D((2, 2))(x)
    x = Conv2D(16, (2, 2), activation='relu', padding='same')(x)
    x = UpSampling2D((2, 2))(x)
    decoded_conv = Conv2D(1, (2, 2), activation='sigmoid', padding='same')(x)


    # Defining the parameters of the Auto-encoder network 
    autoencoder = Model(input_layer, decoded_conv) 
    autoencoder.compile(optimizer ="adadelta", loss ="mse") 
    autoencoder.summary()
        # Training the Auto-encoder network 
    autoencoder.fit(X_train_scaled_conv, X_train_scaled_conv,  
                        batch_size = 3000, epochs = 10,  
                        shuffle = True, validation_split = 0.2) 


    hidden_representation = Sequential() 
    hidden_representation.add(autoencoder.layers[0]) 
    hidden_representation.add(autoencoder.layers[1]) 
    hidden_representation.add(autoencoder.layers[2]) 
    hidden_representation.add(autoencoder.layers[3]) 
    hidden_representation.add(autoencoder.layers[4]) 

        # Separating the points encoded by the Auto-encoder as normal and fraud 
        #nonbuyer_hidden_rep = hidden_representation.predict(X_nonbuyer_scaled) 
        #buyer_hidden_rep = hidden_representation.predict(X_buyer_scaled) 

        # Combining the encoded points into a single table  
        #encoded_X = np.append(nonbuyer_hidden_rep, buyer_hidden_rep, axis = 0) 
        #y_nonbuyer = np.zeros(nonbuyer_hidden_rep.shape[0]) 
        #y_buyer = np.ones(buyer_hidden_rep.shape[0]) 
        #encoded_y = np.append(y_nonbuyer, y_buyer) 
    encoded_X_train = hidden_representation.predict(X_train_scaled_conv) 

    encoded_X_test = hidden_representation.predict(X_test_scaled_conv)


    classifier = SVC() 
    #print("Train data size", encoded_X_train.shape, y_train.shape)
    #print("Train test size", encoded_X_test.shape, y_test.shape)
    #print(len(encoded_X_train))
    encoded_X_train = np.reshape(encoded_X_train, (len(encoded_X_train), i)) 
    encoded_X_test = np.reshape(encoded_X_test, (len(encoded_X_test), i)) 
    classifier.fit(encoded_X_train, y_train) 

        # Storing the predictions of the linear model 
    y_pred_classifier = classifier.predict(encoded_X_test) 


        # Plotting the encoded points 
        #tsne_plot(encoded_X, encoded_y) 


        # Performance
    print('amount of features: ')
    print('Accuracy : '+str(accuracy_score(y_test, y_pred_classifier))) 
    print('Confusion Matrix: \n' + str(confusion_matrix(y_test,y_pred_classifier)))
    tn, fp, fn, tp = confusion_matrix(y_test, y_pred_classifier).ravel()
    print('True negatives: ' + str(tn) + '\n' + 'False positives: ' + str(fp) +  '\n' + 'False negatives: ' + str(fn) + '\n'+ 'True positives: ' + str(tp) + '\n')

    i = i + 1

Model: "model_122"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_61 (InputLayer)        (None, 4, 4, 1)           0         
_________________________________________________________________
conv2d_51 (Conv2D)           (None, 4, 4, 16)          80        
_________________________________________________________________
max_pooling2d_21 (MaxPooling (None, 2, 2, 16)          0         
_________________________________________________________________
conv2d_52 (Conv2D)           (None, 2, 2, 1)           65        
_________________________________________________________________
max_pooling2d_22 (MaxPooling (None, 1, 1, 1)           0         
_________________________________________________________________
conv2d_53 (Conv2D)           (None, 1, 1, 1)           5         
_________________________________________________________________
up_sampling2d_21 (UpSampling (None, 2, 2, 1)           0 

7891/7891 [==============================] - 0s 11us/step - loss: 0.1211 - val_loss: 0.1040
Epoch 8/10
7891/7891 [==============================] - 0s 11us/step - loss: 0.0971 - val_loss: 0.0831
Epoch 9/10
7891/7891 [==============================] - 0s 10us/step - loss: 0.0789 - val_loss: 0.0715
Epoch 10/10
7891/7891 [==============================] - 0s 10us/step - loss: 0.0696 - val_loss: 0.0666
amount of features: 
Accuracy : 0.8373884833738848
Confusion Matrix: 
[[2065    0]
 [ 401    0]]
True negatives: 2065
False positives: 0
False negatives: 401
True positives: 0

Model: "model_125"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_64 (InputLayer)        (None, 4, 4, 1)           0         
_________________________________________________________________
conv2d_66 (Conv2D)           (None, 4, 4, 16)          80        
_________________________________________________________________
max_po

7891/7891 [==============================] - 0s 35us/step - loss: 0.1889 - val_loss: 0.1864
Epoch 2/10
7891/7891 [==============================] - 0s 11us/step - loss: 0.1847 - val_loss: 0.1815
Epoch 3/10
7891/7891 [==============================] - 0s 11us/step - loss: 0.1791 - val_loss: 0.1738
Epoch 4/10
7891/7891 [==============================] - 0s 10us/step - loss: 0.1704 - val_loss: 0.1619
Epoch 5/10
7891/7891 [==============================] - 0s 10us/step - loss: 0.1562 - val_loss: 0.1415
Epoch 6/10
7891/7891 [==============================] - 0s 10us/step - loss: 0.1338 - val_loss: 0.1147
Epoch 7/10
7891/7891 [==============================] - 0s 10us/step - loss: 0.1065 - val_loss: 0.0887
Epoch 8/10
7891/7891 [==============================] - 0s 10us/step - loss: 0.0831 - val_loss: 0.0731
Epoch 9/10
7891/7891 [==============================] - 0s 10us/step - loss: 0.0705 - val_loss: 0.0666
Epoch 10/10
7891/7891 [==============================] - 0s 11us/step - loss: 0.0653

Train on 7891 samples, validate on 1973 samples
Epoch 1/10
7891/7891 [==============================] - 0s 35us/step - loss: 0.1947 - val_loss: 0.1912
Epoch 2/10
7891/7891 [==============================] - 0s 10us/step - loss: 0.1894 - val_loss: 0.1868
Epoch 3/10
7891/7891 [==============================] - 0s 10us/step - loss: 0.1853 - val_loss: 0.1831
Epoch 4/10
7891/7891 [==============================] - 0s 11us/step - loss: 0.1816 - val_loss: 0.1793
Epoch 5/10
7891/7891 [==============================] - 0s 11us/step - loss: 0.1776 - val_loss: 0.1747
Epoch 6/10
7891/7891 [==============================] - 0s 11us/step - loss: 0.1727 - val_loss: 0.1687
Epoch 7/10
7891/7891 [==============================] - 0s 11us/step - loss: 0.1661 - val_loss: 0.1605
Epoch 8/10
7891/7891 [==============================] - 0s 10us/step - loss: 0.1571 - val_loss: 0.1493
Epoch 9/10
7891/7891 [==============================] - 0s 10us/step - loss: 0.1448 - val_loss: 0.1342
Epoch 10/10
7891/7891 [==