# Loading data into pandas dataframe





In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split  

df = pd.read_csv("online_shoppers_intention_numbers.csv")

print(df.columns)

#splitting the Class variable and the features
X = df.drop(columns=['Revenue'])
Y = df['Revenue']

#Making different datasets based on the top 10 features for testing purposes
datasets = {}

X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.2, random_state = 32342) 

In [8]:
# added by Duc, data nomalization
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
scaler.fit(X_train)
X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [9]:
print("Original data")
print(X_train[0:9][:])

Original data
       Administrative  Administrative_Duration  Informational  \
2637               14               230.106944              0   
9415                5               158.700000              0   
11579              11               449.750000              0   
6437                1                22.200000              2   
2198                0                 0.000000              0   
11826               0                 0.000000              4   
5663                0                 0.000000              0   
9553                1                 3.000000              0   
2084                1                 5.000000              0   

       Informational_Duration  ProductRelated  ProductRelated_Duration  \
2637                     0.00              52              2059.109203   
9415                     0.00              51              1364.266667   
11579                    0.00              52              1786.109649   
6437                    44.40          

In [10]:
print("Scaled data")
print(X_train_scaled[0:9][:])

Scaled data
[[5.18518519e-01 6.77034040e-02 0.00000000e+00 0.00000000e+00
  7.37588652e-02 3.21868975e-02 1.87353650e-02 4.22556200e-02
  2.64293485e-02 0.00000000e+00 3.00000000e-01 1.42857143e-01
  8.33333333e-02 0.00000000e+00 6.31578947e-01 5.00000000e-01
  0.00000000e+00]
 [1.85185185e-01 4.66936374e-02 0.00000000e+00 0.00000000e+00
  7.23404255e-02 2.13254894e-02 3.84615400e-02 5.99358950e-02
  0.00000000e+00 0.00000000e+00 9.00000000e-01 2.85714286e-01
  8.33333333e-02 2.50000000e-01 5.26315789e-02 5.00000000e-01
  1.00000000e+00]
 [4.07407407e-01 1.32328062e-01 0.00000000e+00 0.00000000e+00
  7.37588652e-02 2.79195140e-02 0.00000000e+00 8.55932200e-02
  1.41191793e-01 0.00000000e+00 9.00000000e-01 0.00000000e+00
  0.00000000e+00 0.00000000e+00 5.26315789e-02 5.00000000e-01
  0.00000000e+00]
 [3.70370370e-02 6.53181317e-03 8.33333333e-02 1.74160333e-02
  5.24822695e-02 6.26509196e-03 2.56410250e-02 1.28205150e-02
  0.00000000e+00 0.00000000e+00 8.00000000e-01 1.42857143e-01
  7.

In [1]:
datasets.update({"17" : { "X_train": X_train, "X_test": X_test}})
datasets.update({"10" : { "X_train": X_train.drop(columns =['Month', 'TrafficType', 'Informational_Duration', 'OperatingSystems', 'Weekend','Region','Browser']),
                                                 "X_test" : X_test.drop(columns =['Month', 'TrafficType', 'Informational_Duration', 'OperatingSystems', 'Weekend','Region','Browser'])}})
datasets.update({"9": { "X_train": datasets["10"]["X_train"].drop(columns =['SpecialDay']), 
                       "X_test": datasets["10"]["X_test"].drop(columns = ['SpecialDay'])}})
datasets.update({"8": { "X_train": datasets["9"]["X_train"].drop(columns =['Administrative_Duration']), 
                       "X_test": datasets["9"]["X_test"].drop(columns = ['Administrative_Duration'])}})
datasets.update({"7": { "X_train": datasets["8"]["X_train"].drop(columns =['Informational']), 
                       "X_test": datasets["8"]["X_test"].drop(columns = ['Informational'])}})
datasets.update({"6": { "X_train": datasets["7"]["X_train"].drop(columns =['VisitorType']), 
                       "X_test": datasets["7"]["X_test"].drop(columns = ['VisitorType'])}})
datasets.update({"5": { "X_train": datasets["6"]["X_train"].drop(columns =['Administrative']), 
                       "X_test": datasets["6"]["X_test"].drop(columns = ['Administrative'])}})
datasets.update({"4": { "X_train": datasets["5"]["X_train"].drop(columns =['BounceRates']), 
                       "X_test": datasets["5"]["X_test"].drop(columns = ['BounceRates'])}})
datasets.update({"3": { "X_train": datasets["4"]["X_train"].drop(columns =['ProductRelated_Duration']), 
                       "X_test": datasets["4"]["X_test"].drop(columns = ['ProductRelated_Duration'])}})
datasets.update({"2": { "X_train": datasets["3"]["X_train"].drop(columns =['ProductRelated']), 
                       "X_test": datasets["3"]["X_test"].drop(columns = ['ProductRelated'])}})
datasets.update({"1": { "X_train": datasets["2"]["X_train"].drop(columns =['ExitRates']), 
                       "X_test": datasets["2"]["X_test"].drop(columns = ['ExitRates'])}})


#for dataset in datasets:
#    print(datasets[dataset])

print(Y.values)
print(datasets["5"]["X_train"])

Index(['Administrative', 'Administrative_Duration', 'Informational',
       'Informational_Duration', 'ProductRelated', 'ProductRelated_Duration',
       'BounceRates', 'ExitRates', 'PageValues', 'SpecialDay', 'Month',
       'OperatingSystems', 'Browser', 'Region', 'TrafficType', 'VisitorType',
       'Weekend', 'Revenue'],
      dtype='object')
[0 0 0 ... 0 0 0]
       ProductRelated  ProductRelated_Duration  BounceRates  ExitRates  \
2637               52              2059.109203     0.003747   0.008451   
9415               51              1364.266667     0.007692   0.011987   
11579              52              1786.109649     0.000000   0.017119   
6437               37               400.800000     0.005128   0.002564   
2198                2               162.000000     0.000000   0.050000   
...               ...                      ...          ...        ...   
8136               22              2281.583333     0.029697   0.043687   
12078              45              1896.9

In [2]:
# added by Duc for debugging
print("Train data size", X_train.shape, y_train.shape)
print("Train test size", X_test.shape, y_test.shape)

Train data size (9864, 17) (9864,)
Train test size (2466, 17) (2466,)


In [3]:
# added by Duc
import collections
print("number of examples per class in train set:", collections.Counter(y_train))
print("number of examples per class in test set:", collections.Counter(y_test))

number of examples per class in train set: Counter({0: 8357, 1: 1507})
number of examples per class in test set: Counter({0: 2065, 1: 401})


In [5]:
from sklearn.manifold import TSNE 
import matplotlib.pyplot as plt 
%matplotlib inline
import seaborn as sns 

def tsne_plot(x, y):

    sns.set(style ="whitegrid") 
      
    tsne = TSNE(n_components = 2, random_state = 0) 
      
    # Reducing the dimensionality of the data 
    X_transformed = tsne.fit_transform(x) 
  
    plt.figure(figsize =(12, 8)) 
      
    # Building the scatter plot 
    plt.scatter(X_transformed[np.where(y == 0), 0],  
                X_transformed[np.where(y == 0), 1], 
                marker ='o', color ='y', linewidth ='1', 
                alpha = 0.8, label ='Non-Buyer') 
    plt.scatter(X_transformed[np.where(y == 1), 0], 
                X_transformed[np.where(y == 1), 1], 
                marker ='o', color ='k', linewidth ='1', 
                alpha = 0.8, label ='Buyer') 
  
    # Specifying the location of the legend 
    plt.legend(loc ='best') 
      
    # Plotting the reduced data 
    plt.show() 

#tsne_plot(X, Y)

In [21]:

# from sklearn.preprocessing import MinMaxScaler



# for dataset in datasets:
        
#         scaler = MinMaxScaler()
#         datasets[dataset].update({"X_train": scaler.fit_transform(datasets[dataset]["X_train"]), 
#                                   "X_test" : scaler.fit_transform(datasets[dataset]["X_test"])})
    
    
#    # datasets[dataset] = scaler.fit_transform(datasets[dataset])
    
# #scaled_datasets['10'] = X_scaled.drop(columns = ['Month', 'Traffictype', 'Informational_Duration', 'OperatingSystems', 'Weekend','Region','Browser'])
# #scaled_datasets['9'] = X10_scaled.drop(columns =['SpecialDay'])
# #scaled_datasets['8'] = X9_scaled.drop(columns = ['Administrative_Duration'])
# #scaled_datasets['7'] = X8_scaled.drop(columns = ['Informational'])
# #scaled_datasets['6'] = X7_scaled.drop(columns = ['VisitorType'])
# #scaled_datasets['5'] = X6_scaled.drop(columns = ['Administrative'])
# #scaled_datasets['4'] = X5_scaled.drop(columns = ['BounceRates'])
# #scaled_datasets['3'] = X4_scaled.drop(columns = ['ProductRelated_Duration'])
# #scaled_datasets['2'] = X3_scaled.drop(columns = ['ProductRelated'])
# #scaled_datasets['1'] = X2_scaled.drop(columns = ['ExitRates'])




# #tsne_plot(X_scaled, Y)

In [22]:
from sklearn.svm import SVC 
from sklearn.metrics import accuracy_score, confusion_matrix 

# Splitting dataset into train set and test set.
def makepredictions(datasets):
    
    for dataset in datasets:
    
     #   X_train, X_test, y_train, y_test = train_test_split(datasets[dataset], Y, test_size = 0.2, random_state = 32342) 


        svmclf = SVC() 
        svmclf.fit(datasets[dataset]["X_train"], y_train) 

        y_pred_svmclf = svmclf.predict(datasets[dataset]["X_test"]) 
  
        # Performance
        print('amount of features: ' + dataset)
        print('Accuracy : '+str(accuracy_score(y_test, y_pred_svmclf))) 
        print('Confusion Matrix: \n' + str(confusion_matrix(y_test,y_pred_svmclf)))
        # incorrect order of output
#         tn, fn, fp, tp = confusion_matrix(y_test, y_pred_svmclf).ravel()
        # the right order is as follows
        tn, fp, fn, tp = confusion_matrix(y_test, y_pred_svmclf).ravel()
    
        print('True negatives: ' + str(tn) + '\n' + 'False positives: ' + str(fp) +  '\n' + 'False negatives: ' + str(fn) + '\n'+ 'True positives: ' + str(tp) + '\n')

makepredictions(datasets)

amount of features: 17
Accuracy : 0.8722627737226277
Confusion Matrix: 
[[2039   26]
 [ 289  112]]
True negatives: 2039
False positives: 289
False negatives: 26
True positives: 112

amount of features: 10
Accuracy : 0.8811841038118411
Confusion Matrix: 
[[2030   35]
 [ 258  143]]
True negatives: 2030
False positives: 258
False negatives: 35
True positives: 143

amount of features: 9
Accuracy : 0.8815896188158961
Confusion Matrix: 
[[2029   36]
 [ 256  145]]
True negatives: 2029
False positives: 256
False negatives: 36
True positives: 145

amount of features: 8
Accuracy : 0.8819951338199513
Confusion Matrix: 
[[2030   35]
 [ 256  145]]
True negatives: 2030
False positives: 256
False negatives: 35
True positives: 145

amount of features: 7
Accuracy : 0.8832116788321168
Confusion Matrix: 
[[2031   34]
 [ 254  147]]
True negatives: 2031
False positives: 254
False negatives: 34
True positives: 147

amount of features: 6
Accuracy : 0.8860502838605029
Confusion Matrix: 
[[2029   36]
 [ 245  1

In [27]:
from keras.layers import Input, Dense 
from keras.models import Model, Sequential 
from keras import regularizers 
from keras.layers import Input, Dense, Conv2D, MaxPooling2D, UpSampling2D
from keras import backend as K

#scaler = MinMaxScaler()

#X_scaled = scaler.fit_transform(X)
#X_nonbuyer_scaled = X_scaled[Y == 0] 
#X_buyer_scaled = X_scaled[Y == 1]


input_layer = Input(shape =(X.shape[1], )) 

#Encoder network Deep
encoded_deep = Dense(100, activation ='tanh')(input_layer) 
encoded_deep = Dense(50, activation ='tanh')(encoded_deep) 
encoded_deep = Dense(25, activation ='tanh')(encoded_deep) 
encoded_deep = Dense(12, activation ='tanh')(encoded_deep) 
encoded_deep = Dense(6, activation ='relu')(encoded_deep) 

#Decoder network deep
decoded_deep = Dense(12, activation ='tanh')(encoded_deep) 
decoded_deep = Dense(25, activation ='tanh')(decoded_deep) 
decoded_deep = Dense(50, activation ='tanh')(decoded_deep) 
decoded_deep = Dense(100, activation ='tanh')(decoded_deep) 

output_layer_deep = Dense(X.shape[1], activation ='relu')(decoded_deep) 



    # Defining the parameters of the Auto-encoder network 
autoencoder = Model(input_layer, output_layer_deep) 
autoencoder.compile(optimizer ="adadelta", loss ="mse") 

    # Training the Auto-encoder network 
autoencoder.fit(datasets["17"]["X_train"], datasets["17"]["X_train"],  
                    batch_size = 1, epochs = 10,  
                    shuffle = True, validation_split = 0.2) 


hidden_representation = Sequential() 
hidden_representation.add(autoencoder.layers[0]) 
hidden_representation.add(autoencoder.layers[1]) 
hidden_representation.add(autoencoder.layers[2]) 
hidden_representation.add(autoencoder.layers[3]) 
hidden_representation.add(autoencoder.layers[4]) 

    # Separating the points encoded by the Auto-encoder as normal and fraud 
    #nonbuyer_hidden_rep = hidden_representation.predict(X_nonbuyer_scaled) 
    #buyer_hidden_rep = hidden_representation.predict(X_buyer_scaled) 

    # Combining the encoded points into a single table  
    #encoded_X = np.append(nonbuyer_hidden_rep, buyer_hidden_rep, axis = 0) 
    #y_nonbuyer = np.zeros(nonbuyer_hidden_rep.shape[0]) 
    #y_buyer = np.ones(buyer_hidden_rep.shape[0]) 
    #encoded_y = np.append(y_nonbuyer, y_buyer) 
encoded_X_train = hidden_representation.predict(datasets["17"]["X_train"]) 

encoded_X_test = hidden_representation.predict(datasets["17"]["X_test"])


classifier = SVC() 
classifier.fit(encoded_X_train, y_train) 

    # Storing the predictions of the linear model 
y_pred_classifier = classifier.predict(encoded_X_test) 


    # Plotting the encoded points 
    #tsne_plot(encoded_X, encoded_y) 


    # Performance
print('amount of features: ')
print('Accuracy : '+str(accuracy_score(y_test, y_pred_classifier))) 
print('Confusion Matrix: \n' + str(confusion_matrix(y_test,y_pred_classifier)))
tn, fn, fp, tp = confusion_matrix(y_test, y_pred_classifier).ravel()
print('True negatives: ' + str(tn) + '\n' + 'False positives: ' + str(fp) +  '\n' + 'False negatives: ' + str(fn) + '\n'+ 'True positives: ' + str(tp) + '\n')



Train on 7891 samples, validate on 1973 samples
Epoch 1/10
7891/7891 [==============================] - 8s 952us/step - loss: 0.0078 - val_loss: 0.0059
Epoch 2/10
7891/7891 [==============================] - 7s 931us/step - loss: 0.0051 - val_loss: 0.0049
Epoch 3/10
7891/7891 [==============================] - 7s 909us/step - loss: 0.0049 - val_loss: 0.0050
Epoch 4/10
7891/7891 [==============================] - 7s 932us/step - loss: 0.0048 - val_loss: 0.0058
Epoch 5/10
7891/7891 [==============================] - 7s 914us/step - loss: 0.0043 - val_loss: 0.0042
Epoch 6/10
7891/7891 [==============================] - 7s 931us/step - loss: 0.0039 - val_loss: 0.0038
Epoch 7/10
7891/7891 [==============================] - 8s 960us/step - loss: 0.0038 - val_loss: 0.0041
Epoch 8/10
7891/7891 [==============================] - 8s 958us/step - loss: 0.0038 - val_loss: 0.0038
Epoch 9/10
7891/7891 [==============================] - 7s 943us/step - loss: 0.0038 - val_loss: 0.0036
Epoch 10/10
7891

In [35]:
input_layer_sparse = Input(shape =(X.shape[1], )) 

#Encoder network Sparsity constraint
encoded_sparse = Dense(100, activation ='tanh',
activity_regularizer = regularizers.l1(10e-5))(input_layer_sparse) 
encoded_sparse = Dense(50, activation ='tanh',
activity_regularizer = regularizers.l1(10e-5))(encoded_sparse) 
encoded_sparse = Dense(25, activation ='tanh', 
activity_regularizer = regularizers.l1(10e-5))(encoded_sparse) 
encoded_sparse = Dense(12, activation ='tanh', 
activity_regularizer = regularizers.l1(10e-5))(encoded_sparse) 
encoded_sparse = Dense(6, activation ='relu')(encoded_sparse) 

#Decoder network Sparsity constraint
decoded_sparse = Dense(12, activation ='tanh')(encoded_sparse) 
decoded_sparse = Dense(25, activation ='tanh')(decoded_sparse) 
decoded_sparse = Dense(50, activation ='tanh')(decoded_sparse) 
decoded_sparse = Dense(100, activation ='tanh')(decoded_sparse) 

output_layer_sparse = Dense(X.shape[1], activation ='relu')(decoded_sparse) 



# Defining the parameters of the Auto-encoder network 
autoencoder = Model(input_layer_sparse, output_layer_sparse) 
autoencoder.compile(optimizer ="adadelta", loss ="mse") 

# Training the Auto-encoder network 
autoencoder.fit(datasets["17"]["X_train"], datasets["17"]["X_train"],  
                    batch_size = 3000, epochs = 7,  
                    shuffle = True, validation_split = 0.2) 


hidden_representation = Sequential() 
hidden_representation.add(autoencoder.layers[0]) 
hidden_representation.add(autoencoder.layers[1]) 
hidden_representation.add(autoencoder.layers[2]) 
hidden_representation.add(autoencoder.layers[3]) 
hidden_representation.add(autoencoder.layers[4]) 

    # Separating the points encoded by the Auto-encoder as normal and fraud 
    #nonbuyer_hidden_rep = hidden_representation.predict(X_nonbuyer_scaled) 
    #buyer_hidden_rep = hidden_representation.predict(X_buyer_scaled) 

    # Combining the encoded points into a single table  
    #encoded_X = np.append(nonbuyer_hidden_rep, buyer_hidden_rep, axis = 0) 
    #y_nonbuyer = np.zeros(nonbuyer_hidden_rep.shape[0]) 
    #y_buyer = np.ones(buyer_hidden_rep.shape[0]) 
    #encoded_y = np.append(y_nonbuyer, y_buyer) 
encoded_X_train = hidden_representation.predict(datasets["17"]["X_train"]) 

encoded_X_test = hidden_representation.predict(datasets["17"]["X_test"])


classifier = SVC() 
classifier.fit(encoded_X_train, y_train) 

    # Storing the predictions of the linear model 
y_pred_classifier = classifier.predict(encoded_X_test) 


    # Plotting the encoded points 
    #tsne_plot(encoded_X, encoded_y) 


    # Performance
print('amount of features: ')
print('Accuracy : '+str(accuracy_score(y_test, y_pred_classifier))) 
print('Confusion Matrix: \n' + str(confusion_matrix(y_test,y_pred_classifier)))
tn, fn, fp, tp = confusion_matrix(y_test, y_pred_classifier).ravel()
print('True negatives: ' + str(tn) + '\n' + 'False positives: ' + str(fp) +  '\n' + 'False negatives: ' + str(fn) + '\n'+ 'True positives: ' + str(tp) + '\n')


Train on 7891 samples, validate on 1973 samples
Epoch 1/7
7891/7891 [==============================] - 0s 49us/step - loss: 6.6220 - val_loss: 4.2390
Epoch 2/7
7891/7891 [==============================] - 0s 4us/step - loss: 5.6310 - val_loss: 3.7217
Epoch 3/7
7891/7891 [==============================] - 0s 5us/step - loss: 4.9941 - val_loss: 3.3590
Epoch 4/7
7891/7891 [==============================] - 0s 4us/step - loss: 4.5488 - val_loss: 3.0926
Epoch 5/7
7891/7891 [==============================] - 0s 4us/step - loss: 4.2198 - val_loss: 2.8748
Epoch 6/7
7891/7891 [==============================] - 0s 4us/step - loss: 3.9388 - val_loss: 2.6991
Epoch 7/7
7891/7891 [==============================] - 0s 4us/step - loss: 3.7147 - val_loss: 2.5390
amount of features: 
Accuracy : 0.8665855636658556
Confusion Matrix: 
[[2059    6]
 [ 323   78]]
True negatives: 2059
False positives: 323
False negatives: 6
True positives: 78



In [11]:
#Encoder network Convolutional
input_layer = Input(shape =(X.shape[1], )) 

x = Conv2D(16, (3, 3), activation='relu', padding='same')(input_layer)
x = MaxPooling2D((2, 2), padding='same')(x)
x = Conv2D(8, (3, 3), activation='relu', padding='same')(x)
x = MaxPooling2D((2, 2), padding='same')(x)
x = Conv2D(8, (3, 3), activation='relu', padding='same')(x)
encoded_conv = MaxPooling2D((2, 2), padding='same')(x)

# at this point the representation is (4, 4, 8) i.e. 128-dimensional

x = Conv2D(8, (3, 3), activation='relu', padding='same')(encoded_conv)
x = UpSampling2D((2, 2))(x)
x = Conv2D(8, (3, 3), activation='relu', padding='same')(x)
x = UpSampling2D((2, 2))(x)
x = Conv2D(16, (3, 3), activation='relu')(x)
x = UpSampling2D((2, 2))(x)
decoded_conv = Conv2D(1, (3, 3), activation='sigmoid', padding='same')(x)


# Defining the parameters of the Auto-encoder network 
autoencoder = Model(input_layer, output_layer) 
autoencoder.compile(optimizer ="adadelta", loss ="mse") 

    # Training the Auto-encoder network 
autoencoder.fit(datasets["17"]["X_train"], datasets["17"]["X_train"],  
                    batch_size = 3000, epochs = 10,  
                    shuffle = True, validation_split = 0.2) 


hidden_representation = Sequential() 
hidden_representation.add(autoencoder.layers[0]) 
hidden_representation.add(autoencoder.layers[1]) 
hidden_representation.add(autoencoder.layers[2]) 
hidden_representation.add(autoencoder.layers[3]) 
hidden_representation.add(autoencoder.layers[4]) 

    # Separating the points encoded by the Auto-encoder as normal and fraud 
    #nonbuyer_hidden_rep = hidden_representation.predict(X_nonbuyer_scaled) 
    #buyer_hidden_rep = hidden_representation.predict(X_buyer_scaled) 

    # Combining the encoded points into a single table  
    #encoded_X = np.append(nonbuyer_hidden_rep, buyer_hidden_rep, axis = 0) 
    #y_nonbuyer = np.zeros(nonbuyer_hidden_rep.shape[0]) 
    #y_buyer = np.ones(buyer_hidden_rep.shape[0]) 
    #encoded_y = np.append(y_nonbuyer, y_buyer) 
encoded_X_train = hidden_representation.predict(datasets["17"]["X_train"]) 

encoded_X_test = hidden_representation.predict(datasets["17"]["X_test"])


classifier = SVC() 
classifier.fit(encoded_X_train, y_train) 

    # Storing the predictions of the linear model 
y_pred_classifier = classifier.predict(encoded_X_test) 


    # Plotting the encoded points 
    #tsne_plot(encoded_X, encoded_y) 


    # Performance
print('amount of features: ')
print('Accuracy : '+str(accuracy_score(y_test, y_pred_classifier))) 
print('Confusion Matrix: \n' + str(confusion_matrix(y_test,y_pred_classifier)))
tn, fn, fp, tp = confusion_matrix(y_test, y_pred_classifier).ravel()
print('True negatives: ' + str(tn) + '\n' + 'False positives: ' + str(fp) +  '\n' + 'False negatives: ' + str(fn) + '\n'+ 'True positives: ' + str(tp) + '\n')



NameError: name 'Input' is not defined